[package]
name = "token_store"
version = "0.1.2"
authors = ["Victor Berger <victor.berger@m4x.org>"]
documentation = "https://docs.rs/token_store"
repository = "https://github.com/vberger/token_store"
license = "MIT"
description = "A token-based store for arbitrary values"
